apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team1
  name: team1-role
rules:
- apiGroups: [""]
  resources: ["applications", "appprojects", "apptemplates"]
  verbs: ["get", "list", "create", "update", "delete"]

---

# tenant1-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team1-role-binding
  namespace: team1
subjects:
- kind: ServiceAccount
  name: tenant1-service-account
roleRef:
  kind: Role
  name: team1-role
  apiGroup: rbac.authorization.k8s.io